//! This module introduces [`BackpressuredBroadcaster`], a custom
//! implementation of [`WorkersBroadcaster`].

use {
    async_trait::async_trait,
    log::{debug, warn},
    solana_tpu_client_next::{
        ConnectionWorkersSchedulerError, WireTransaction,
        connection_workers_scheduler::WorkersBroadcaster,
        workers_cache::{WorkersCache, WorkersCacheError},
    },
    std::net::SocketAddr,
    tokio::time::{Duration, Instant, timeout_at},
};

const MAX_BROADCAST_WAIT: Duration = Duration::from_millis(100);

/// [`BackpressuredBroadcaster`] distributes transactions among `ConnectionWorker`s while applying
/// backpressure.
///
/// It initially attempts to send transactions to all specified peers, similar to
/// [`NonblockingBroadcaster`](solana_tpu_client_next::connection_workers_scheduler::NonblockingBroadcaster).
/// If all attempts fail due to full channels, it falls back to blocking transmission with a
/// shared 25 ms deadline across the selected workers. If the deadline expires, the transaction is
/// dropped so the scheduler can refresh its leader targets. This applies brief backpressure when
/// the cluster cannot process transactions as fast as they are generated by `transaction-bench`.
///
/// Empirical results show that this approach of sending to the first available peer performs
/// similarly to an alternative strategy where transactions are sent **concurrently and blockingly**
/// to all peers, canceling the others as soon as one accepts them.
pub struct BackpressuredBroadcaster;

#[async_trait]
impl WorkersBroadcaster for BackpressuredBroadcaster {
    async fn send_to_workers(
        &self,
        workers: &mut WorkersCache,
        leaders: &[SocketAddr],
        transaction: WireTransaction,
    ) -> Result<(), ConnectionWorkersSchedulerError> {
        // this part is taken from NonblockingBroadcaster with modification of
        // counting successful try_send.
        let mut num_delivered: usize = 0;
        for new_leader in leaders {
            if !workers.contains(new_leader) {
                warn!("No existing worker for {new_leader:?}, skip sending to this leader.");
                continue;
            }

            let send_res = workers.try_send_transaction_to_address(new_leader, transaction.clone());
            match send_res {
                Ok(()) => num_delivered = num_delivered.saturating_add(1),
                Err(WorkersCacheError::ShutdownError) => {
                    debug!("Connection to {new_leader} was closed, worker cache shutdown");
                }
                Err(WorkersCacheError::ReceiverDropped) => {
                    // do nothing here, we shutdown the worker in try_send_transaction_to_address
                }
                Err(err) => {
                    debug!("Failed to send transaction to {new_leader}, worker error: {err}");
                    // If we have failed to send transaction, it will be dropped.
                }
            }
        }

        if num_delivered != 0 {
            // If we managed to enqueue with at least one worker it is good
            // enough. See doc comment for the [`BackpressuredBroadcaster`]
            // definition.
            return Ok(());
        }

        // Bound the entire fallback so an unresponsive peer cannot prevent
        // the scheduler from refreshing its leader targets.
        let deadline = Instant::now() + MAX_BROADCAST_WAIT;
        for new_leader in leaders {
            if !workers.contains(new_leader) {
                continue;
            }

            let send_res = match timeout_at(
                deadline,
                workers.send_transaction_to_address(new_leader, transaction.clone()),
            )
            .await
            {
                Ok(send_res) => send_res,
                Err(_) => {
                    debug!(
                        "Broadcast queue wait exceeded {MAX_BROADCAST_WAIT:?}; dropping \
                         transaction so the scheduler can refresh leader targets."
                    );
                    return Ok(());
                }
            };
            match send_res {
                Ok(()) => {
                    // Delivery to a single leader is enough.
                    return Ok(());
                }
                Err(WorkersCacheError::ShutdownError) => {
                    debug!("Connection to {new_leader} was closed, worker cache shutdown");
                }
                Err(WorkersCacheError::ReceiverDropped) => {
                    // do nothing here, we shutdown the worker in send_transaction_to_address
                }
                Err(WorkersCacheError::WorkerNotFound) => {
                    debug!("No existing worker for {new_leader:?}, skip sending to this leader.");
                }
                Err(WorkersCacheError::FullChannel | WorkersCacheError::TaskJoinFailure) => {
                    unreachable!(
                        "send_transaction_to_address does not try-send or join worker tasks."
                    );
                }
            }
        }

        // Fail to enqueue due to the queues being full and/or the leaders
        // disconnecting. The client will still need to verify transaction
        // landed by subscribing to transaction events and/or checking the block
        // content. We don't return error here because errors of this method are
        // treated as critical. If tpu-client-next implement a strategy to
        // handle non-critical errors somehow, return here such that that the
        // client would know that their transaction was not queued at all, and
        // could retry faster. They still need to rely on checks later in the
        // processing chain, but a faster retry could improve latency for cases
        // when the leaders are overloaded.
        Ok(())
    }
}
