name: Compile

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - master
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "rust-toolchain.toml"
      - ".github/workflows/compile.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SHELL: /bin/bash
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    if: github.event.pull_request.base.repo.full_name == 'anza-xyz/tpu-tools' && !github.event.pull_request.draft
    name: check and test
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696  # v0.0.10
        with:
          version: "v0.10.0"

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y \
            libclang-dev \
            libprotobuf-dev \
            libssl-dev \
            libudev-dev \
            pkg-config \
            zlib1g-dev \
            llvm \
            clang \
            cmake \
            make \
            protobuf-compiler

      - name: Setup Rust
        shell: bash
        run: |
          rustup show active-toolchain || rustup toolchain install
          rustup toolchain install nightly-2026-02-28 --profile minimal --component rustfmt --component clippy
          cargo +nightly-2026-02-28 install cargo-sort --locked

      - name: Format
        shell: bash
        run: cargo +nightly-2026-02-28 fmt --all

      - name: Sort
        shell: bash
        run: cargo +nightly-2026-02-28 sort --workspace

      - name: Check
        shell: bash
        run: cargo +nightly-2026-02-28 check --locked --workspace --all-targets

      - name: Clippy
        shell: bash
        run: cargo +nightly-2026-02-28 clippy --workspace --all-targets -- --deny=warnings --deny=clippy::default_trait_access --deny=clippy::arithmetic_side_effects --deny=clippy::manual_let_else --deny=clippy::uninlined-format-args --deny=clippy::used_underscore_binding

      - name: Test
        shell: bash
        run: cargo test --locked --workspace --all-targets
